const state = { health:null, sources:[], profiles:[], functions:[], datasets:[], lots:[], runs:[], users:[], selected:null, reports:[], selectedRun:null, selectedBatch:null, selectedFunctions:new Set(), workspaceRuns:[] };
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const esc = value => String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[char]));
const title = value => String(value ?? "").replaceAll("_", " ").replace(/\b\w/g, char => char.toUpperCase());
const actor = () => $("#actor").value;
const formatDate = value => value ? new Date(value).toLocaleString() : "—";
const short = value => value ? `${String(value).slice(0, 8)}…` : "—";
const json = value => esc(JSON.stringify(value ?? {}, null, 2));

async function api(url, options = {}) {
  const headers = { "x-cbcr-user": actor(), ...(options.headers || {}) };
  if (options.body) headers["content-type"] = "application/json";
  const response = await fetch(`/api/v1${url}`, { ...options, headers });
  if (!response.ok) {
    const payload = await response.json().catch(() => ({}));
    throw new Error(payload.detail || `${response.status} ${response.statusText}`);
  }
  return response.status === 204 ? null : response.json();
}
function toast(message, error = false) {
  const node = $("#toast"); node.textContent = message; node.className = error ? "show error" : "show";
  window.clearTimeout(toast.timer); toast.timer = window.setTimeout(() => { node.className = ""; }, 4200);
}
function status(value) { return `<span class="status ${esc(value)}">${esc(title(value))}</span>`; }
function nav(view) { $$("#navigation button").forEach(button => button.classList.toggle("active", button.dataset.view === view)); $$(".view").forEach(section => section.classList.toggle("active", section.id === view)); if (view === "runs") renderRuns(); if (view === "cases") loadCases(); if (view === "governance") renderGovernance(); if (view === "catalogue") renderCatalogue(); if (view === "admin") renderAdmin(); }

function safeTask(task, fallback) { return task.catch(() => fallback); }
async function refreshCore() {
  const [health, sources, profiles, functions, datasets, lots, runs, users] = await Promise.all([
    api("/health"), safeTask(api("/sources"), []), safeTask(api("/pipeline-profiles"), []), safeTask(api("/functions"), []), safeTask(api("/datasets"), []), safeTask(api("/lots"), []), safeTask(api("/runs"), []), safeTask(api("/users"), [])
  ]);
  Object.assign(state, { health, sources, profiles, functions, datasets, lots, runs, users });
  renderShell(); renderWork(); renderLifecycle(); renderCatalogue(); renderAdmin();
}
function renderShell() {
  const health = state.health || {}; const database = health.database || {};
  $("#systemStatus").textContent = `${String(health.persistence_backend || "offline").toUpperCase()} · ${database.database || "—"}`;
  $("#healthPanel").innerHTML = [
    ["Backend", health.persistence_backend || "unavailable"], ["Database", database.database || "—"], ["Application user", database.username || "—"], ["Async workers", "CONTROL PLANE ACTIVE"]
  ].map(([label, value]) => `<div class="health-cell"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`).join("");
  const known = [...new Set(["demo", "auditor", ...state.users.map(user => user.user_id)])];
  const prior = actor(); $("#actor").innerHTML = known.map(user => `<option value="${esc(user)}" ${user === prior ? "selected" : ""}>${esc(user)}</option>`).join("");
  const sourceOptions = state.sources.map(source => `<option value="${esc(source.source_id)}">${esc(source.name)}</option>`).join("");
  const profileOptions = state.profiles.map(profile => `<option value="${esc(profile.profile_id)}">${esc(profile.name)}</option>`).join("");
  $("#intakeSource").innerHTML = sourceOptions; $("#intakeProfile").innerHTML = profileOptions;
}
function renderWork() {
  const active = state.runs.filter(run => ["queued", "running"].includes(run.status));
  const canonical = state.datasets.filter(dataset => dataset.zone === "canonical").length;
  const waiting = state.datasets.filter(dataset => ["dq_passed", "enriched"].includes(dataset.zone)).length;
  const risk = state.datasets.filter(dataset => dataset.zone === "risk_ready").length;
  const cards = [["ACTIVE RUNS", active.length, "Monitor asynchronous work", "runs"], ["DQ WORK", canonical, "Canonical snapshots awaiting review", "lifecycle"], ["PUBLICATION WORK", waiting, "DQ-passed or enriched snapshots", "lifecycle"], ["RISK READY", risk, "Datasets available for risk/case work", "lifecycle"]];
  $("#workQueue").innerHTML = cards.map(([label, count, text, view]) => `<article class="queue-card"><p class="kicker">${label}</p><h2>${count}</h2><p>${text}</p><button class="text-button" data-nav="${view}">OPEN →</button></article>`).join("");
  $("#recentRuns").innerHTML = state.runs.slice(0, 6).map(run => `<div class="compact-row">${status(run.status)}<strong>${esc(short(run.run_id))}</strong><small>${esc(title(run.purpose))} · ${esc(formatDate(run.created_at))}</small><button class="text-button" data-run="${esc(run.run_id)}">INSPECT →</button></div>`).join("") || `<div class="empty-note">No runs are visible to this user.</div>`;
  $$('[data-nav]').forEach(button => button.onclick = () => nav(button.dataset.nav)); $$('[data-run]').forEach(button => button.onclick = () => { nav("runs"); inspectRun(button.dataset.run); });
}
function lotName(lot) { return lot.external_lot_ref || `Lot ${short(lot.lot_id)}`; }
function renderLifecycle() {
  const requestedLot = $("#lotFilter").value; const requestedZone = $("#zoneFilter").value;
  $("#lotFilter").innerHTML = `<option value="">All lots</option>${state.lots.map(lot => `<option value="${esc(lot.lot_id)}" ${lot.lot_id === requestedLot ? "selected" : ""}>${esc(lotName(lot))}</option>`).join("")}`;
  const visible = state.datasets.filter(dataset => (!requestedLot || dataset.lot_id === requestedLot) && (!requestedZone || dataset.zone === requestedZone));
  const grouped = new Map(); visible.forEach(dataset => { const group = grouped.get(dataset.lot_id) || []; group.push(dataset); grouped.set(dataset.lot_id, group); });
  $("#lifecycleList").innerHTML = [...grouped.entries()].map(([lotId, datasets]) => { const lot = state.lots.find(item => item.lot_id === lotId) || {}; return `<section class="lot-group"><div class="lot-head"><div><p class="kicker">Intake lot</p><h2>${esc(lotName(lot))}</h2><code>${esc(lotId)}</code></div><small>${esc(formatDate(lot.created_at))}</small></div><div class="dataset-rail">${datasets.sort((a,b) => a.created_at.localeCompare(b.created_at)).map(datasetCard).join("")}</div></section>`; }).join("") || `<div class="empty-note">No datasets match the selected filters.</div>`;
  $$('[data-dataset]').forEach(button => button.onclick = () => openDataset(button.dataset.dataset, Number(button.dataset.version)));
}
function datasetCard(dataset) { return `<article class="dataset-card zone-${esc(dataset.zone)}"><span class="zone">${esc(title(dataset.zone))}</span><strong>${esc(short(dataset.dataset_id))}</strong><small>v${esc(dataset.version)} · ${esc(dataset.report_count)} reports</small><code>${esc(dataset.pipeline_profile_id)}</code><button class="secondary" data-dataset="${esc(dataset.dataset_id)}" data-version="${esc(dataset.version)}">OPEN WORKSPACE</button></article>`; }
function nextZone(dataset) { const profile = state.profiles.find(item => item.profile_id === dataset.pipeline_profile_id); if (!profile) return null; const index = profile.route.indexOf(dataset.zone); return index < 0 ? null : profile.route[index + 1] || null; }

async function openDataset(datasetId, version) {
  const dataset = state.datasets.find(item => item.dataset_id === datasetId && Number(item.version) === Number(version)) || await api(`/datasets/${datasetId}/versions/${version}`);
  state.selected = dataset; state.reports = await safeTask(api(`/datasets/${datasetId}/versions/${version}/reports`), []); state.selectedFunctions.clear(); state.workspaceRuns = [];
  $("#workspaceEmpty").hidden = true; $("#workspaceContent").hidden = false; renderWorkspace(); nav("workspace");
}
function renderWorkspace() {
  const dataset = state.selected; if (!dataset) return; const next = nextZone(dataset);
  $("#datasetBanner").innerHTML = [["Lot", dataset.lot_id], ["Dataset", dataset.dataset_id], ["Zone", title(dataset.zone)], ["Profile", dataset.pipeline_profile_id], ["Reports", dataset.report_count]].map(([label, value]) => `<div><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`).join("");
  renderOverview(); renderData(); renderFunctionPicker(); renderResults(); renderPublish(); renderLineage();
  $("#workspaceTabs").dataset.next = next || "";
}
function renderOverview() { const dataset = state.selected; const entities = state.reports.reduce((sum, report) => sum + (report.entities || []).length, 0); const metrics = state.reports.reduce((sum, report) => sum + (report.metrics || []).length, 0); const next = nextZone(dataset); $("#overviewContent").innerHTML = `<div class="metric-grid"><article class="metric"><span>Reports</span><strong>${dataset.report_count}</strong></article><article class="metric"><span>Entities</span><strong>${entities}</strong></article><article class="metric"><span>Metrics</span><strong>${metrics}</strong></article><article class="metric"><span>Next governed move</span><strong>${esc(next ? title(next) : "Final")}</strong></article></div><div class="info-grid"><section class="panel"><p class="kicker">Operating context</p><h2>${esc(title(dataset.zone))} snapshot</h2><p>This immutable dataset is the only context used by functions and publication actions opened here.</p><button class="command" data-tab-link="functions">RUN FUNCTIONS</button></section><section class="panel"><p class="kicker">Publication readiness</p><h2>${next ? `Next: ${title(next)}` : "Pipeline complete"}</h2><p>${next ? "Review results and use the Publish / enrich tab when the required evidence is available." : "Risk and case functions can be run independently from this risk-ready snapshot."}</p><button class="secondary" data-tab-link="publish">OPEN PUBLISHING</button></section></div>`; $$('[data-tab-link]').forEach(button => button.onclick = () => activateTab(button.dataset.tabLink)); }
function renderData() { const rows = state.reports.map(report => `<tr><td><code>${esc(report.report_id)}</code></td><td>${esc(report.reporting_entity_name)}</td><td>${esc(report.reporting_entity_id)}</td><td>${esc(report.reporting_period_end)}</td><td>${esc((report.entities || []).length)}</td><td>${esc((report.metrics || []).length)}</td></tr>`).join(""); $("#dataContent").innerHTML = `<section class="panel"><div class="panel-head"><div><p class="kicker">Snapshot record preview</p><h2>Reports and entities</h2></div><span>${state.reports.length} loaded</span></div><div class="data-toolbar"><input id="reportSearch" placeholder="Filter by report ID or reporting entity"></div><div class="table-wrap"><table><thead><tr><th>Report</th><th>Reporting entity</th><th>Entity ID</th><th>Period end</th><th>Constituents</th><th>Metrics</th></tr></thead><tbody id="reportRows">${rows || `<tr><td colspan="6">No report records found.</td></tr>`}</tbody></table></div></section>`; $("#reportSearch").oninput = event => { const query = event.target.value.toLowerCase(); $$("#reportRows tr").forEach(row => row.hidden = !row.textContent.toLowerCase().includes(query)); }; }
function applicableFunctions() { const allowed = { canonical:["01","02","03","04"], dq_passed:["03","04"], enriched:["03","04"], risk_ready:["05","06","07"] }; return state.functions.filter(fn => (allowed[state.selected.zone] || []).includes(fn.stage)); }
function inputFor(code, key, spec) { const value = Array.isArray(spec.default) ? spec.default.join(",") : spec.default ?? ""; if (spec.type === "boolean") return `<label>${esc(title(key))}<input data-param="${esc(code)}:${esc(key)}" type="checkbox" ${spec.default ? "checked" : ""}></label>`; return `<label>${esc(title(key))}<input data-param="${esc(code)}:${esc(key)}" type="${spec.type === "number" || spec.type === "integer" ? "number" : "text"}" value="${esc(value)}"></label>`; }
function renderFunctionPicker() { const rows = applicableFunctions(); $("#functionsContent").innerHTML = `<section class="panel"><div class="panel-head"><div><p class="kicker">${esc(title(state.selected.zone))} functions</p><h2>Run independent controls</h2></div><span>${rows.length} available</span></div><p>Choose one or more controls. Parameters are scoped to the function that uses them; each selected function executes independently in one asynchronous parent run.</p><div class="function-grid">${rows.map(fn => `<article class="function-card ${state.selectedFunctions.has(fn.code) ? "selected" : ""}"><header><input type="checkbox" data-function="${esc(fn.code)}" ${state.selectedFunctions.has(fn.code) ? "checked" : ""}><div><span class="zone">Stage ${esc(fn.stage)} · ${esc(title(fn.purpose))}</span><h3>${esc(fn.name)}</h3></div></header><p>${esc(fn.description)}</p><div class="parameter-grid">${Object.entries(fn.parameter_schema || {}).map(([key,spec]) => inputFor(fn.code,key,spec)).join("") || `<span class="empty-note">No input parameters</span>`}</div></article>`).join("") || `<div class="empty-note">No active functions are configured for this zone.</div>`}</div><div class="function-actions"><span id="functionSummary">${state.selectedFunctions.size} selected</span><button class="command" id="queueDatasetRun">QUEUE ASYNCHRONOUS RUN</button></div></section>`; $$('[data-function]').forEach(box => box.onchange = () => { box.checked ? state.selectedFunctions.add(box.dataset.function) : state.selectedFunctions.delete(box.dataset.function); renderFunctionPicker(); }); $("#queueDatasetRun").onclick = queueDatasetRun; }
function parseParam(spec, input) { if (spec.type === "boolean") return input.checked; if (spec.type === "number") return Number(input.value); if (spec.type === "integer") return parseInt(input.value, 10); if (spec.type === "array") return input.value.split(",").map(item => item.trim()).filter(Boolean); return input.value; }
async function queueDatasetRun() { if (!state.selectedFunctions.size) return toast("Select at least one function.", true); const selectedFunctions = applicableFunctions().filter(fn => state.selectedFunctions.has(fn.code)); const purposes = new Set(selectedFunctions.map(fn => fn.purpose)); if (purposes.size !== 1) return toast("Choose functions from one purpose per run.", true); const parameters = {}; selectedFunctions.forEach(fn => { parameters[fn.code] = {}; Object.entries(fn.parameter_schema || {}).forEach(([key,spec]) => { const input = document.querySelector(`[data-param="${CSS.escape(`${fn.code}:${key}`)}"]`); if (input) parameters[fn.code][key] = parseParam(spec,input); }); });
  try { const result = await api("/dataset-runs", { method:"POST", body:JSON.stringify({ dataset_id:state.selected.dataset_id, dataset_version:state.selected.version, input_zone:state.selected.zone, report_ids:null, functions:selectedFunctions.map(fn=>fn.code), parameters, purpose:[...purposes][0] }) }); state.workspaceRuns.unshift(result.run_id); state.runs.unshift({ run_id:result.run_id,status:"queued",purpose:[...purposes][0],created_at:new Date().toISOString(),source_id:"dataset" }); toast(`Run ${short(result.run_id)} queued.`); activateTab("results"); pollRun(result.run_id); } catch(error) { toast(error.message,true); } }
async function pollRun(runId, attempts=0) { try { const run = await api(`/runs/${runId}`); if (["queued","running"].includes(run.status) && attempts < 60) return window.setTimeout(() => pollRun(runId,attempts+1), 900); renderResults(); renderWork(); } catch (_) {} }
function renderResults() { const ids = state.workspaceRuns; $("#resultsContent").innerHTML = `<section class="panel"><div class="panel-head"><div><p class="kicker">Execution evidence</p><h2>Dataset run results</h2></div><button class="secondary" id="refreshWorkspaceResults">REFRESH</button></div><div id="workspaceRunList" class="compact-list">${ids.length ? ids.map(id => `<div class="compact-row"><strong>${esc(short(id))}</strong><small>Loading run evidence…</small><button class="text-button" data-workspace-run="${esc(id)}">OPEN →</button></div>`).join("") : `<div class="empty-note">Runs submitted from this workspace appear here. Older runs remain available in Run history.</div>`}</div><div id="workspaceRunDetail"></div></section>`; $("#refreshWorkspaceResults").onclick = () => ids.forEach(id => openWorkspaceRun(id)); $$('[data-workspace-run]').forEach(button => button.onclick = () => openWorkspaceRun(button.dataset.workspaceRun)); }
async function openWorkspaceRun(runId) { try { const [run,findings] = await Promise.all([api(`/runs/${runId}`),api(`/runs/${runId}/findings`)]); const list = $("#workspaceRunList"); const existing = list.querySelector(`[data-workspace-run="${CSS.escape(runId)}"]`)?.parentElement; if(existing) existing.innerHTML = `${status(run.status)}<strong>${esc(short(runId))}</strong><small>${esc(title(run.purpose))} · ${esc(run.function_runs.length)} functions</small><button class="text-button" data-workspace-run="${esc(runId)}">OPEN →</button>`; $("#workspaceRunDetail").innerHTML = runDetailMarkup(run,findings); $$('[data-workspace-run]').forEach(button => button.onclick = () => openWorkspaceRun(button.dataset.workspaceRun)); } catch(error) { toast(error.message,true); } }
function runDetailMarkup(run, findings) { return `<div class="run-inspector"><div class="panel-head"><h2>Run ${esc(short(run.run_id))}</h2>${status(run.status)}</div><div class="child-grid">${run.function_runs.map(child => `<article class="child-card"><span class="zone">Stage ${esc(child.stage)}</span><strong>${esc(title(child.function_code))}</strong>${status(child.status)}<pre>${json(child.summary || child.error || {})}</pre></article>`).join("")}</div><h3>Findings (${findings.length})</h3>${findings.map(finding => `<article class="finding ${esc(finding.severity)}"><h4>${esc(finding.code)}</h4><small>${esc(finding.function_code)} · ${esc(finding.report_id || "dataset")} ${finding.jurisdiction ? `· ${esc(finding.jurisdiction)}` : ""}</small><p>${esc(finding.message)}</p><code>${json(finding.evidence)}</code></article>`).join("") || `<div class="empty-note">No findings generated. This is a valid successful outcome when the run completed.</div>`}</div>`; }
function renderPublish() { const dataset = state.selected; const next = nextZone(dataset); if (!next) { $("#publishContent").innerHTML = `<div class="empty-note">This profile has no further publication zone. Run risk and case-review functions from the risk-ready snapshot.</div>`; return; } if(dataset.zone === "canonical") { $("#publishContent").innerHTML = `<section class="panel"><p class="kicker">DQ gate</p><h2>Evaluate and publish DQ-passed data</h2><p>Select a completed run ID from Run history or one submitted in this workspace. The gate evaluates the supplied run's findings only.</p><label>Completed DQ run ID<input id="gateRunId" value="${esc(state.workspaceRuns[0] || "")}" placeholder="Run ID"></label><label>Blocking severities<select id="gateSeverity" multiple><option value="error" selected>Error</option><option value="warning">Warning</option></select></label><div class="function-actions"><span>Review dispositions before publishing.</span><button class="command" id="evaluateGate">EVALUATE GATE</button></div><div id="gateOutput"></div></section>`; $("#evaluateGate").onclick = evaluateGate; return; }
  if(dataset.zone === "dq_passed" && next === "enriched") { $("#publishContent").innerHTML = `<section class="panel"><p class="kicker">Governed enrichment</p><h2>Publish enriched snapshot</h2><p>Add optional report- or entity-level attributes with source and confidence. Select identifiers from this dataset; never type a blank entity ID.</p><div class="enrichment-grid"><label>Report<select id="enrichmentReport">${state.reports.map(report => `<option value="${esc(report.report_id)}">${esc(report.report_id)} · ${esc(report.reporting_entity_name)}</option>`).join("")}</select></label><label>Entity scope<select id="enrichmentEntity"><option value="">Report-level (no entity)</option></select></label><label>Attribute name<input id="enrichmentName" value="domestic_registry_status"></label><label>Value<input id="enrichmentValue" value="active"></label><label>Source reference<input id="enrichmentSource" value="demo-domestic-registry"></label><label>Confidence<input id="enrichmentConfidence" type="number" min="0" max="1" step="0.01" value="0.95"></label></div><label>Publication reason<input id="promotionReason" value="Niche governed enrichment publication"></label><div class="function-actions"><span>Creates a new immutable enriched dataset.</span><button class="command" id="promoteEnriched">PUBLISH ENRICHED</button></div></section>`; $("#enrichmentReport").onchange = renderEntityOptions; renderEntityOptions(); $("#promoteEnriched").onclick = promoteEnriched; return; }
  $("#publishContent").innerHTML = `<section class="panel"><p class="kicker">Governed publication</p><h2>Publish ${esc(title(next))}</h2><p>This creates a new immutable snapshot and preserves the current dataset as its parent.</p><label>Publication reason<input id="promotionReason" value="Niche governed publication"></label><div class="function-actions"><span>${esc(title(dataset.zone))} → ${esc(title(next))}</span><button class="command" id="promoteNext">PUBLISH ${esc(title(next))}</button></div></section>`; $("#promoteNext").onclick = () => promote(next,[],null); }
function renderEntityOptions() { const report = state.reports.find(item => item.report_id === $("#enrichmentReport").value); $("#enrichmentEntity").innerHTML = `<option value="">Report-level (no entity)</option>${(report?.entities || []).map(entity => `<option value="${esc(entity.entity_id)}">${esc(entity.entity_id)} · ${esc(entity.name)}</option>`).join("")}`; }
async function evaluateGate() { const runId=$("#gateRunId").value.trim(); if(!runId) return toast("Enter a completed DQ run ID.",true); try { const levels=[...$("#gateSeverity").selectedOptions].map(option=>option.value); const evaluation=await api(`/datasets/${state.selected.dataset_id}/versions/${state.selected.version}/evaluate-promotion`,{method:"POST",body:JSON.stringify({run_id:runId,blocking_severities:levels})}); const dispositions=await api(`/evaluations/${evaluation.evaluation_id}/dispositions`); $("#gateOutput").innerHTML=`<div class="panel"><h3>Gate result</h3><p>${esc(evaluation.eligible_count)} eligible · ${esc(evaluation.rejected_count)} rejected</p><div class="compact-list">${dispositions.map(item=>`<div class="compact-row">${status(item.disposition)}<strong>${esc(item.report_id)}</strong><small>${esc((item.reason_codes || []).join(", ") || "No blocking findings")}</small></div>`).join("")}</div><button class="command" id="publishDq" data-evaluation="${esc(evaluation.evaluation_id)}">PUBLISH DQ-PASSED</button></div>`; $("#publishDq").onclick=()=>promote("dq_passed",[],evaluation.evaluation_id); } catch(error) { toast(error.message,true); } }
async function promoteEnriched() { const entity=$("#enrichmentEntity").value || null; const value={report_id:$("#enrichmentReport").value,entity_id:entity,attribute_name:$("#enrichmentName").value,value:$("#enrichmentValue").value,source_ref:$("#enrichmentSource").value,confidence:Number($("#enrichmentConfidence").value)}; promote("enriched",[value],null); }
async function promote(target,enrichmentValues,evaluationId) { try { const response=await api(`/datasets/${state.selected.dataset_id}/versions/${state.selected.version}/promote`,{method:"POST",body:JSON.stringify({target_zone:target,evaluation_id:evaluationId,enrichment_values:enrichmentValues,reason:$("#promotionReason")?.value || "Niche governed publication"})}); toast(`${title(target)} dataset published.`); await refreshCore(); await openDataset(response.target_dataset_id,response.target_version); } catch(error) { toast(error.message,true); } }
async function renderLineage() { if(!state.selected) return; $("#lineageContent").innerHTML=`<div class="empty-note">Loading lineage…</div>`; try { const value=await api(`/datasets/${state.selected.dataset_id}/versions/${state.selected.version}/lineage`); const dataset=value.dataset || {}; $("#lineageContent").innerHTML=`<section class="panel"><p class="kicker">Immutable provenance</p><h2>${esc(title(dataset.zone || state.selected.zone))} lineage</h2><div class="lineage-event"><strong>Current snapshot</strong><br><code>${esc(dataset.dataset_id)}</code></div>${(dataset.parents || []).map(parent=>`<div class="lineage-event"><strong>${esc(title(parent.transition))}</strong><br><code>${esc(parent.parent_dataset_id)}</code><br><small>${esc(parent.reason || "No reason recorded")}</small></div>`).join("") || `<div class="empty-note">No parent relation returned.</div>`}<h3>Promotion events</h3>${(value.promotions || []).map(event=>`<div class="compact-row"><strong>${esc(title(event.source_zone))} → ${esc(title(event.target_zone))}</strong><small>${esc(event.promoted_count)} promoted · ${esc(event.rejected_count)} rejected · ${esc(formatDate(event.created_at))}</small></div>`).join("")}</section>`; } catch(error) { $("#lineageContent").innerHTML=`<div class="empty-note">${esc(error.message)}</div>`; } }
function activateTab(tab) { $$("#workspaceTabs button").forEach(button=>button.classList.toggle("active",button.dataset.tab===tab)); $$(".workspace-tab").forEach(section=>section.classList.toggle("active",section.id===`tab-${tab}`)); if(tab === "lineage") renderLineage(); }

function renderRuns() { const wantedStatus=$("#runStatus").value; const wantedPurpose=$("#runPurpose").value; const rows=state.runs.filter(run=>(!wantedStatus||run.status===wantedStatus)&&(!wantedPurpose||run.purpose===wantedPurpose)); $("#runHistory").innerHTML=rows.map(run=>`<article class="run-row">${status(run.status)}<code>${esc(run.run_id)}</code><span>${esc(title(run.purpose))}</span><small>${esc(formatDate(run.created_at))}</small><button class="text-button" data-inspect-run="${esc(run.run_id)}">INSPECT →</button></article>`).join("")||`<div class="empty-note">No visible runs match these filters.</div>`; $$('[data-inspect-run]').forEach(button=>button.onclick=()=>inspectRun(button.dataset.inspectRun)); }
async function inspectRun(runId) { try { const [run,findings]=await Promise.all([api(`/runs/${runId}`),api(`/runs/${runId}/findings`)]); state.selectedRun=runId; $("#runInspector").innerHTML=`<section class="panel">${runDetailMarkup(run,findings)}</section>`; } catch(error) { toast(error.message,true); } }
async function loadCases() { $("#batchList").innerHTML=`<div class="empty-note">Loading batches…</div>`; try { const batches=await api("/selection-batches"); $("#batchList").innerHTML=batches.map(batch=>`<div class="compact-row">${status(batch.status)}<strong>${esc(short(batch.selection_batch_id))}</strong><small>Run ${esc(short(batch.run_id))} · ${esc(formatDate(batch.created_at))}</small><button class="text-button" data-batch="${esc(batch.selection_batch_id)}">OPEN →</button></div>`).join("")||`<div class="empty-note">No selection batches are visible.</div>`; $$('[data-batch]').forEach(button=>button.onclick=()=>openBatch(button.dataset.batch)); } catch(error) { $("#batchList").innerHTML=`<div class="empty-note">${esc(error.message)}</div>`; } }
async function openBatch(batchId) { state.selectedBatch=batchId; try { const candidates=await api(`/selection-batches/${batchId}/candidates`); $("#candidateList").innerHTML=candidates.map(candidate=>`<article class="candidate"><div>${status(candidate.decision)} <strong>${esc(candidate.entity_name || candidate.report_id)}</strong></div><small>${esc(candidate.report_id)} · ${esc(candidate.reason_code)} · score ${esc(candidate.score)}</small><pre class="candidate-evidence">${json(candidate.evidence)}</pre>${candidate.decision === "pending" ? `<div class="decision-row"><select data-decision="${esc(candidate.candidate_id)}"><option value="selected">Selected for review</option><option value="rejected">Rejected</option><option value="deferred">Deferred</option></select><textarea data-rationale="${esc(candidate.candidate_id)}" rows="2" placeholder="Decision rationale required"></textarea><button class="command" data-save-decision="${esc(candidate.candidate_id)}">SAVE DECISION</button></div>` : `<small>Decision by ${esc(candidate.decided_by || "—")} · ${esc(formatDate(candidate.decided_at))}</small>`}</article>`).join("")||`<div class="empty-note">No candidates in this batch.</div>`; $$('[data-save-decision]').forEach(button=>button.onclick=()=>saveDecision(button.dataset.saveDecision)); } catch(error) { $("#candidateList").innerHTML=`<div class="empty-note">${esc(error.message)}</div>`; } }
async function saveDecision(candidateId) { const decision=document.querySelector(`[data-decision="${CSS.escape(candidateId)}"]`).value; const rationale=document.querySelector(`[data-rationale="${CSS.escape(candidateId)}"]`).value.trim(); if(!rationale) return toast("A decision rationale is required.",true); try { await api(`/selection-candidates/${candidateId}/decision`,{method:"PUT",body:JSON.stringify({decision,rationale})}); toast("Candidate decision persisted."); openBatch(state.selectedBatch); } catch(error) { toast(error.message,true); } }
function renderGovernance() { const target=$("#governanceLineage"); if(state.selected) { target.innerHTML=`<button class="command" id="openWorkspaceLineage">OPEN ${esc(title(state.selected.zone))} LINEAGE</button>`; $("#openWorkspaceLineage").onclick=()=>{nav("workspace");activateTab("lineage");}; } }
async function loadAudit() { try { const events=await api("/audit?limit=100"); $("#auditList").innerHTML=events.map(event=>`<article class="audit-row">${status(event.decision)} <strong>${esc(event.action)}</strong> <small>${esc(event.actor)} · ${esc(formatDate(event.created_at))}</small><br><code>${esc(event.target_ref)}</code></article>`).join("")||`<div class="empty-note">No audit events returned.</div>`; } catch(error) { $("#auditList").innerHTML=`<div class="empty-note">${esc(error.message)}. Use the auditor role to view access/action audit events.</div>`; } }
function renderCatalogue() { const groups={}; state.functions.forEach(fn=>(groups[fn.stage] ||= []).push(fn)); $("#catalogueList").innerHTML=Object.entries(groups).sort().map(([stage,items])=>`<section class="catalogue-card"><p class="kicker">Stage ${esc(stage)}</p>${items.map(fn=>`<article><span class="zone">${esc(title(fn.purpose))} · v${esc(fn.version)}</span><h2>${esc(fn.name)}</h2><code>${esc(fn.code)}</code><p>${esc(fn.description)}</p><small>${Object.keys(fn.parameter_schema || {}).length ? `Parameters: ${esc(Object.keys(fn.parameter_schema).join(", "))}` : "No parameters"}</small></article>`).join("<hr>")}</section>`).join("")||`<div class="empty-note">No active functions are visible.</div>`; }
function renderAdmin() { $("#sourceList").innerHTML=state.sources.map(source=>`<div class="compact-row">${status(source.adapter_type)}<strong>${esc(source.name)}</strong><small>${esc(source.endpoint_link)}</small><code>${esc(source.source_id)}</code></div>`).join("")||`<div class="empty-note">No sources visible.</div>`; $("#userList").innerHTML=state.users.map(user=>`<div class="compact-row"><strong>${esc(user.display_name)}</strong><code>${esc(user.user_id)}</code><small>${esc((user.roles || []).join(", "))}</small></div>`).join("")||`<div class="empty-note">User/role listing requires access-management permission.</div>`; $("#profileList").innerHTML=state.profiles.map(profile=>`<article class="profile-row"><strong>${esc(profile.name)}</strong><code>${esc(profile.profile_id)}</code><span class="profile-route">${esc((profile.route || []).join(" → "))}</span></article>`).join(""); }

async function submitIntake(event) { event.preventDefault(); const reportIds=$("#intakeReportIds").value.split(",").map(value=>value.trim()).filter(Boolean); try { const result=await api("/lots",{method:"POST",body:JSON.stringify({source_id:$("#intakeSource").value,pipeline_profile_id:$("#intakeProfile").value,external_lot_ref:$("#intakeReference").value.trim()||null,report_ids:reportIds.length?reportIds:null,metadata:{note:$("#intakeNote").value.trim(),submitted_from:"Niche"}})}); $("#intakeDialog").close(); toast(`Lot ${short(result.lot_id)} created.`); await refreshCore(); await openDataset(result.canonical_dataset.dataset_id,result.canonical_dataset.version); } catch(error) { toast(error.message,true); } }
function bindEvents() {
  $$("#navigation button").forEach(button=>button.onclick=()=>nav(button.dataset.view)); $("#lotFilter").onchange=renderLifecycle; $("#zoneFilter").onchange=renderLifecycle; $("#runStatus").onchange=renderRuns; $("#runPurpose").onchange=renderRuns; $("#actor").onchange=async()=>{ try { await refreshCore(); toast(`Reloaded as ${actor()}.`); } catch(error) { toast(error.message,true); } }; $$("[data-action]").forEach(button=>button.onclick=()=>handleAction(button.dataset.action)); $$("#workspaceTabs button").forEach(button=>button.onclick=()=>activateTab(button.dataset.tab)); $("#intakeForm").addEventListener("submit",submitIntake);
}
async function handleAction(action) { if(action === "open-intake") return $("#intakeDialog").showModal(); if(action === "refresh-lifecycle") { await refreshCore(); return toast("Lifecycle refreshed."); } if(action === "refresh-runs") { await refreshCore(); renderRuns(); return; } if(action === "refresh-cases") return loadCases(); if(action === "load-audit") return loadAudit(); if(action === "refresh-catalogue") { await refreshCore(); return toast("Catalogue refreshed."); } }
async function init() { bindEvents(); try { await refreshCore(); } catch(error) { $("#systemStatus").textContent="OFFLINE"; toast(error.message,true); } }
init();
